//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommentTable
    {
        public string Comment { get; set; }
        public string Username { get; set; }
        public int Like { get; set; }
        public int Unlike { get; set; }
        public string Id { get; set; }
        public int blogid { get; set; }
    }
    public class BlogViewModel
    {
        public IEnumerable<CommentTable> PreviousComment { get; set; }
        public CommentTable NewComment { get; set; }
        public IEnumerable<BlogTable> BlogList { get; set; }
        public int blogid;
        public string likeid;
    }
}
