//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIP.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class DataTable
    {
        public string modifiedby { get; set; }
        public int id { get; set; }
        public string data1 { get; set; }
        public string data2 { get; set; }
        public string data3 { get; set; }

    }

    public partial class FileModel
    {
        public HttpPostedFileBase UploadedFile { get; set; }        
    }
    public partial class DataTableModel
    {
        public IEnumerable<DataTable> allData { get; set; }
        public int pageCount { get; set; }
        public int pageNo { get; set; }
    }
}
